
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 05 12:25:30 CST 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NombreComprador = 2;
  public static final int CodigoPostal = 3;
  public static final int DescripcionArticulo = 7;
  public static final int ERROR = 9;
  public static final int Cantidad = 5;
  public static final int EOF = 0;
  public static final int Precio = 6;
  public static final int Ubicacion = 4;
  public static final int error = 1;
  public static final int Guion = 8;
}

